---
- name: Chaos Monkey
  hosts: all
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: localhost
        port: 8445
  rules:
    - name: debug
      condition: True
      action:
        debug:
