---
- name: Chaos Monkey
  hosts: all
  sources:
    - name: listen for alerts
      ansible.eda.alertmanager:
        host: host.containers.internal
        port: 84456
  rules:
    - name: debug
      condition: True
      action:
        debug:
