---
- name: Chaos Monkey
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: "No more sql injection"
      condition: True
      action:
        debug:
          msg: "How would I do that?"

