---
- name: Chaos Monkey
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    action:
      run_module:
        name: ansible.builtin.debug
        module_args:
          msg: "foobar cmeyers printed"
