---
- name: Chaos Monkey
  hosts: all
  gather_facts: true
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: "output a message to file /tmp/outme.log"
      condition: True
      action:
        run_module:
          name: ansible.builtin.shell
          module_args:
            cmd: 'echo "hello world" > /tmp/outme.log'

    - name: "output a message to the screen"
      condition: True
      action:
        run_module:
          name: ansible.builtin.shell
          module_args:
            cmd: 'cat /tmp/outme.log'

    - name: "this rule will have sql injection ' or 'a'='a"
      condition: True
      action:
        debug:
          msg: "How would I do that?"
