---
- name: Chaos Monkey
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: "output a message to file /tmp/outme.log"
      action:
        run_module:
          name: ansible.builtin.shell
          module_args:
            cmd: 'dkfjdljf "hello world" > /tmp/outme.log'

    - name: "read from outputted file"
      action:
        debug:
          msg: "How would I do that?"
