---
- name: Demo Job Template launcher
  hosts: all
  sources:
    - ansible.eda.range:
        limit: 5
  rules:
    - name: Launch the Demo Job Template
      condition: event.i == 1
      action:
        run_job_template:
          msg: "Demo Job Template"
